# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a73d37b0468ba56c16bee349a4f3ca35b3afb0436f3ff0bf83e635003db5a856d5bd3ebb7bfc47fa8ea6edc7046b85958d33e2927c9e03576b07f5520058cfc3

test:
  secret_key_base: 35fee94bf4c429459885109a6899fe996e0a57615089094026f7d311b4abe9212bc5567cc5f056ae06be305297013346c86d544b6ecfaba7ecaa07d0a14f466f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
